import { loadRegister, loadProgram, buildLedger, ceilingFor } from './data.js';
import { prepare, simulateWithAttribution, simulate, withCeilings } from './sim.js';
import { DEFAULT_SETTINGS, PERILS } from './assume.js';
import { sampleRegisterCSV, SAMPLE_PROGRAM_CSV } from './samples.js';
import { rankContributors } from './findings.js';
const m=n=> (n>=1e6? '$'+(n/1e6).toFixed(n>=100e6?0:1)+'M' : '$'+Math.round(n/1e3)+'k');
const {contracts}=loadRegister(sampleRegisterCSV());
const program=loadProgram(SAMPLE_PROGRAM_CSV);
const ledger=buildLedger(contracts,program);
const s={...DEFAULT_SETTINGS,trials:25000};
const prep=prepare(contracts,program,ledger,s);
const r=simulateWithAttribution(prep,s);
const sumCaps=contracts.reduce((a,c)=>a+(isFinite(c.cap)?c.cap:0),0);
console.log('book', m(contracts.reduce((a,c)=>a+c.annualValue,0)), '| contracts', contracts.length, '| uncapped', contracts.filter(c=>!isFinite(c.cap)).length);
console.log('sumCaps', m(sumCaps));
console.log('gross',m(r.gross.mean),'transferred',m(r.transferred.mean));
console.log('RETAINED mean',m(r.retained.mean),'p90',m(r.retained.p90),'p99',m(r.retained.p99),'tvar99',m(r.retained.tvar99));
console.log('defence',m(r.defence.total),(r.defence.shareOfGross*100).toFixed(0)+'%','retained',m(r.defence.retained),'eroding',m(r.defence.erodingLimits));
console.log('noForm',m(r.split.uninsuredByForm));
console.log('GL exhaust',(r.aggregates.find(a=>a.group==='GL-PRIMARY').exhaustionProb*100).toFixed(0)+'%');
const ranked=rankContributors(contracts,r,25);
const tighten=(map,c,i,p,prop)=>{const cur=ceilingFor(c,p);const nx=Math.min(cur,prop);if(nx<cur)map.set(i+'|'+p,nx);};
const top=new Map(); ranked.slice(0,10).forEach(x=>{const c=contracts[x.index];PERILS.forEach(p=>{if(p!=='GROSS')tighten(top,c,x.index,p,c.annualValue*3)})});
const all=new Map(); contracts.forEach((c,i)=>PERILS.forEach(p=>{if(p!=='GROSS')tighten(all,c,i,p,c.annualValue*5)}));
const rt=simulate(withCeilings(prep,top),s), ra=simulate(withCeilings(prep,all),s);
console.log('lever top10: p99',m(rt.retained.p99),'removed',m(r.retained.p99-rt.retained.p99));
console.log('lever bookwide: p99',m(ra.retained.p99),'removed',m(r.retained.p99-ra.retained.p99));
console.log('share', (((r.retained.p99-rt.retained.p99)/(r.retained.p99-ra.retained.p99))*100).toFixed(0)+'%');
